apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-example02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/liorhaim/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./custom-diff/02-external-app
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example02

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
  https://learning.codefresh.io/path-player?courseid=gitops-at-scale&unit=62f63d43ccb64a6f2c3e8304Unit:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /metadata/annotations/creation
    - group: *
      kind: Secret
      jsonPointers:
      - /data/my-password
   
